# Generated by Django 4.2.10 on 2024-03-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSongaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='arrived',
            field=models.BooleanField(default=True),
        ),
    ]
