# Generated by Django 4.2.10 on 2024-03-21 00:44

import appSongaz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSongaz', '0002_file_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='unique_id',
            field=models.CharField(default=appSongaz.models.generate_unique_id, max_length=4, unique=True),
        ),
    ]
